### ISSUE TITLE
Trouble understanding the configuration

### ISSUE THREAD

**Issue by scheusal333** [wjansenw/duplicati-homeassistant#1]
First of all, thanks for sharing this project. 
I would like to implement it in my setup.
Im not an expert, so maybe its just because of that, that i dont understand how to set it up.

maybe you can give some details about the setup.
confusing to me is this part: 

> In` the current flow, this file is to be stored on /data/duplicati/duplicati_config.yaml

should i just adjust the content and save the yaml in this folder manually or is this done somehow by the flow?

sorry for the noob question

**Comment by wjansenw** [comment]
HI @scheusal333 ,
Yes, you will need to have that file in the location, and update it with the duplicati instance(s) you want to monitor as well as the mqtt broker details.

Note: i just uploaded a newer version. I have removed all sensors, keeping only the switch and moved the other info to attributes. You can always create sensor templates from the attributes in case you want to.
Reason: I was getting many errors in HA, so decided to simplify the node-red flow. Now I do not seem to be getting errors anymore.

Regards,
Wim

**Comment by scheusal333** [comment]
Thanks for your answer.
Unfortunately it seems like Im not able to create the duplicati_config.yaml

Im using HAos, but neihter using  SSH Webterminal nor using Portainer command line Im allowed to create the file, because nano is not supported :(.
Seems like this is the downside of using HAos with addons instead of real Docker Setup.

**Comment by wjansenw** [comment]
You can create it outside the container and copy it to the container. Or
use vi or other editors.

Op di 23 jan 2024 19:18 schreef scheusal333 ***@***.***>:

**Comment by wjansenw** [comment]
Just to check. You are in the nodered container, right?

**Comment by scheusal333** [comment]
No i actually thought it needs to be in Duplicati container.
This was part of my initial question.

In Duplicati container there is already a directory "/data/duplicati/"
In Node red conteiner, there is no such directory. Do I need to create it there?

**Comment by scheusal333** [comment]
is it fine to just change the path in the node red flow in Discovery "input file"  to a path that i can enter, for example /share ?
just tried it and node red seems to find it. But ihm not sure if this is the only part were this file is used.

**Comment by wjansenw** [comment]
Yes, that should be fine.

Op wo 24 jan 2024 18:26 schreef scheusal333 ***@***.***>:

**Comment by wjansenw** [comment]
This is the only place you should modify.



Op wo 24 jan 2024 18:31 schreef Wim Jansen ***@***.***>:

**Comment by wjansenw** [comment]
![Screenshot_20240124_183314_Chrome](https://github.com/wjansenw/duplicati-homeassistant/assets/25421739/2e9bc14c-32aa-4771-ae76-146277bf6922)

**Comment by scheusal333** [comment]
great thank you, will test that soon

**Comment by scheusal333** [comment]
its working :)

initially it puts out some object error (I dont remember exactly) and did not connect to mosquitto.
I had to set the MQTT node manually to connect properly. 
Now it seems to work fine.

Thanks for sharing and your friendly support
